CVE-2016-4430
VulnerabilityHistoryProject/struts-vulnerabilities pull request #37
Opened 2019-10-23 18:33 UTC by Chrestopher

2019-10-30 00:56 UTC, mesternefeld commented on cves/CVE-2016-4430.yml
> +    apache confluence, CVE page references
I'm not sure what this is, can you elaborate?

2019-10-30 23:35 UTC, Chrestopher commented on cves/CVE-2016-4430.yml
> +    apache confluence, CVE page references
Thank you! I have replaced this with a more detailed explanation beyond the reference to sites.

2019-10-31 14:17 UTC, Bgood12 commented on cves/CVE-2016-4430.yml
> +announced: 2016-05-02
You're claiming that the vulnerability was announced prior to it being reported by the team. If the vulnerability was made public the team would likely learn of it quickly, double-check this.

2019-10-31 23:28 UTC, Chrestopher commented on cves/CVE-2016-4430.yml
> +announced: 2016-05-02
Ok im not too sure on this actually. The dev confluence page of the vulnerability (https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=65143300) was created on 2016-06-11, but the CVE entry was created or the ID was reserved on 2016-05-02. (https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-4430)

2019-11-01 14:24 UTC, yerngpaii requested changes
Since this vulnerability has to do with xss, wouldn't defense in depth be applicable ?

2019-11-01 15:55 UTC, Chrestopher commented on cves/CVE-2016-4430.yml
> +announced: 2016-05-02
Just pushed a change for this. The CVE date could have just been a reservation so I found another resource where the vulnerability was announced publicly.

2019-11-01 16:02 UTC, Chrestopher commented
> Since this vulnerability has to do with xss, wouldn't defense in depth be applicable ?

Defense is depth is where someone knew something was secure, but added an extra layer just in case. In this vulnerability, the xxrf was more so a result of carelessness.

2019-11-01 16:29 UTC, yerngpaii commented
> > Since this vulnerability has to do with xss, wouldn't defense in depth be applicable ?
> 
> Defense is depth is where someone knew something was secure, but added an extra layer just in case. In this vulnerability, the xxrf was more so a result of carelessness.

I see, thanks for clarifying. I give this 3 upvotes

2020-02-20 19:47 UTC, merged