CVE-2016-3090
VulnerabilityHistoryProject/struts-vulnerabilities pull request #47
Opened 2019-10-26 17:47 UTC by adw4236

2019-10-26 20:29 UTC, exl5325 requested changes

2019-10-26 20:29 UTC, exl5325 commented on cves/CVE-2016-3090.yml
> +  answer: |
This is a good writeup. I'd also argue that it is a maintainability mistake. If it is that easy to create new vulnerabilities whenever any new feature is added, there is probably something wrong or missing in the team's maintenance process. Typically you'd expect to see some form of regression testing whenever a new feature is added and it looks like Apache either didn't do that or its regression testing missed a fairly obvious bug.

2019-10-26 20:29 UTC, exl5325 commented on cves/CVE-2016-3090.yml
> +  Expression Language that is maily meant to access data within an object using
nit: maily -> mainly

2019-10-26 20:29 UTC, exl5325 commented on cves/CVE-2016-3090.yml
> +    applies: true
It might also be prudent to add that OGNL is extremely vulnerable to injections (like you mentioned above), so adding even more security checks to anything coming from OGNL would be a good mitigation

2019-10-26 20:29 UTC, exl5325 commented on cves/CVE-2016-3090.yml
> +    from the unit tests that could be exploited.  The fix also updated these unit tests
Got any examples of a missing test case that could've caught this issue?

2019-10-26 20:29 UTC, exl5325 commented on cves/CVE-2016-3090.yml
> +description: |
This is a really good description

2019-10-26 20:29 UTC, exl5325 commented on cves/CVE-2016-3090.yml
> +  into the equifax breach (CVE-2017-5638).
Seems like Apache should get around to patching OGNL as well

2019-10-26 20:29 UTC, exl5325 commented on cves/CVE-2016-3090.yml
> +    Technically, this vulnerability was likely to be existant before the VCC due to it
https://www.cvedetails.com/cve/CVE-2016-3090/

It seems like the vulnerability affected every version of Struts 2 since the beginning, so I agree with you in that it is likely the bug has existed since the application was first written. This might be something you want to either add somewhere

2019-10-29 00:31 UTC, adw4236 commented on cves/CVE-2016-3090.yml
> +    from the unit tests that could be exploited.  The fix also updated these unit tests
Unfortunately, I could not find anything, they were really vague about what actually caused it, this article is the closest thing, but it doesn't say anything about this vulnerability specifically which seems to be related to ANTLR.
https://pentest-tools.com/blog/exploiting-ognl-injection-in-apache-struts/

2019-10-29 00:36 UTC, adw4236 commented on cves/CVE-2016-3090.yml
> +  answer: |
It's hard to know exactly what their update process and regression testing is, this could be something they consider for new updates or at least during code reviews, but the process could be a lot easier and more secure than relying on people remembering to do it.

2020-02-20 19:01 UTC, merged