CVE-2016-4465
VulnerabilityHistoryProject/struts-vulnerabilities pull request #6
Opened 2019-03-21 21:52 UTC by PaulGildehaus

The report on CVE-2016-4465 has been filled out fully for round 1.

2019-03-25 18:40 UTC, MattThyng commented on cves/CVE-2016-4465.yml
> +reported: 2016-05-02T00:00Z
Please use the YYYY-MM-DD format

2019-03-25 18:40 UTC, MattThyng commented on cves/CVE-2016-4465.yml
> +announced: 2016-05-02T00:00Z
Please use the YYYY-MM-DD format

2019-03-25 19:52 UTC, MattThyng commented on cves/CVE-2016-4465.yml
> +  answer: |
What can be done to prevent future coding mistakes?

2019-03-26 17:25 UTC, PaulGildehaus commented on cves/CVE-2016-4465.yml
> +reported: 2016-05-02T00:00Z
Fixed! Thanks for the feedback

2019-03-26 17:25 UTC, PaulGildehaus commented on cves/CVE-2016-4465.yml
> +announced: 2016-05-02T00:00Z
Fixed!

2019-03-26 17:26 UTC, PaulGildehaus commented on cves/CVE-2016-4465.yml
> +  answer: |
Added more commentary! Thank you for pointing out that I missed that.

2019-03-29 01:51 UTC, blh2666 commented
This could just be me missing something obvious, but I can't find where you list the commit that introduced the vulnerability, or the commit that fixed it.

2019-03-29 02:02 UTC, blh2666 requested changes

2019-03-29 02:02 UTC, blh2666 commented on cves/CVE-2016-4465.yml
> +      The input that allowed for this vulnerability is immensely complex. There is a
I would personally disagree with this. While the input itself is complex, the mistake itself was very simple in both execution and to understand it.

2019-03-29 02:04 UTC, blh2666 commented
I found this vulnerability pretty interesting. Its weird to think something so system breaking can be so simple.

2019-03-29 02:31 UTC, camilo86 commented
The fact that a simple null URL can take down the whole server is pretty wild. From a development standpoint, I would expect this sort of input to be tested right away as the feature was built as it is a **very** common edge case when dealing with strings. I would vote this 2 points

2019-03-29 03:50 UTC, PaulGildehaus commented on cves/CVE-2016-4465.yml
> +      The input that allowed for this vulnerability is immensely complex. There is a
I disagree. My reasoning for this is that since the input possibilities are so complex, this allowed the bug to exist. There were too many checks required because of the complex input, and there was at least one vulnerability bound to get through the regex.

2019-09-18 00:13 UTC, merged